<!DOCTYPE html>
<html lang='pl'>
<head>
	<meta charser="UTF-8">
	<title>My Page</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="keywords" content="Patryk, Piwko">
	<link rel="stylesheet" href="OnePage/OnePage/public/css/style.css">

	<!-- [if lt IE 9]>
	<script>https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js</script>
	<![endif]-->
</head>
<body>
	<nav>
	
	</nav>
	<article>
	
	</article>
</body>
</html>