<!DOCTYPE html>
<html lang='pl'>
<head>
	<meta charser="UTF-8">
	<title>My Page</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="keywords" content="Patryk, Piwko">
	<link rel="stylesheet" href="OnePage/OnePage/public/css/style.css">

	<!-- [if lt IE 9]>
	<script>https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js</script>
	<![endif]-->
</head>
<body>
	<section id="content">
		<header>
			<h2 class="logo">Moje portfolio</h2>
			<nav>
				<ul class="menu">
					<li><a href="#">Strona Główna</a></li>
					<li><a href="#">O mnie</a></li>
					<li><a href="#">Kontakt</a></li>
				</ul>
			</nav>
		</header>
		<article>
		wrwrw
		</article>
	</section>
	<footer class="container-footer">
	sdfs
	</footer>
</body>
</html>